CREATE TABLE IF NOT EXISTS `uctoo_weicj` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`keyword`  varchar(100) NOT NULL  COMMENT '关键词',
`keyword_type`  tinyint(2) NOT NULL  DEFAULT 0 COMMENT '关键词类型',
`title`  varchar(255) NOT NULL  COMMENT '标题',
`intro`  text NOT NULL  COMMENT '封面简介',
`pic3`  int(10) UNSIGNED NOT NULL  COMMENT '场景图三',
`cover`  int(10) UNSIGNED NOT NULL  COMMENT '封面图片',
`pic2`  int(10) UNSIGNED NOT NULL  COMMENT '场景图二',
`mp_id` int(10) NOT NULL COMMENT '公众号ID',
`pic1`  int(10) UNSIGNED NOT NULL  COMMENT '场景图一',
`pic4`  int(10) UNSIGNED NOT NULL  COMMENT '场景图四',
`pic5`  int(10) UNSIGNED NOT NULL  COMMENT '场景图五',
`pic6`  int(10) UNSIGNED NOT NULL  COMMENT '场景图六',
`clickpic`  int(10) UNSIGNED NOT NULL  COMMENT '场景跳转图',
`andio`  int(10) UNSIGNED NOT NULL  COMMENT '背景音乐',
`cjurl`  varchar(255) NOT NULL  DEFAULT 'http://' COMMENT '场景跳转URL',
`audio2`  varchar(255) NOT NULL  COMMENT '背景音乐（网络地址）',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;

INSERT INTO `uctoo_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('weicj','微场景','0','','1','{"1":["title","keyword","cover","intro","pic1","pic2","pic3","pic4","pic5","pic6","clickpic","audio2","andio","cjurl"]}','1:基础','','','','','title:15%标题\r\nkeyword:10%关键词\r\nintro:30%简介\r\ncjurl:30%微场景跳转URL\r\nid:操作:[EDIT]|编辑,[DELETE]|删除','10','title','','1396061373','1415106338','1','MyISAM');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('keyword','关键词','varchar(100) NOT NULL','string','','','1','','0','1','1','1396624337','1396061575','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('keyword_type','关键词类型','tinyint(2) NOT NULL','select','0','','0','0:完全匹配\r\n1:左边匹配\r\n2:右边匹配\r\n3:模糊匹配','0','1','1','1415092655','1396061765','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','标题','varchar(255) NOT NULL','string','','','1','','0','1','1','1396624461','1396061859','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('intro','封面简介','text NOT NULL','textarea','','','1','','0','0','1','1396624505','1396061947','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pic3','场景图三','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1415086918','1415086918','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cover','封面图片','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1396624534','1396062093','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pic2','场景图二','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1415086892','1415086892','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('mp_id','公众号ID','int(10) NOT NULL','num','','','0','','0','0','1','1396602871','1396602859','','3','','regex','get_mpid','1','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pic1','场景图一','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1415086865','1415086865','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pic4','场景图四','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1415086953','1415086953','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pic5','场景图五','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1415086986','1415086986','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pic6','场景图六','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1415087003','1415087003','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('clickpic','场景跳转图','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1415087060','1415087060','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('andio','背景音乐','int(10) UNSIGNED NOT NULL','file','','','1','','0','0','1','1415088267','1415088267','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cjurl','场景跳转URL','varchar(255) NOT NULL','string','http://','','1','','0','0','1','1415106528','1415088306','','3','','regex','','3','function');
INSERT INTO `uctoo_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('audio2','背景音乐（网络地址）','varchar(255) NOT NULL','string','','网络地址和附件选填一项','1','','0','0','1','1415092477','1415092477','','3','','regex','','3','function');
UPDATE `uctoo_attribute` SET model_id= (SELECT MAX(id) FROM `uctoo_model`) WHERE model_id=0;